title: "Tevy Tunsay"
description: "Write an awesome description for your site."
permalink: "/:title/"
baseurl: "/Whats-on-my-mind"
url: "https://tevy27.github.io"

# Author
author: "Tevy Tunsay"
author-img: "tevy-tunsay.jpeg"
about-author: "I am a web developer focusing on front-end development."
social-github: "tevy27"
social-linkedin: "tunsaytevy2711"
social-email: "tunsaytevy@gmail.com"

# Build
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
